# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_pic',
            field=models.ImageField(default='mainapp/image/no_img.jpg', upload_to='mainapp/static/mainapp/image'),
        ),
    ]
