# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(default='', max_length=50)),
                ('facebook', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Film_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visiter_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=200)),
                ('note', models.CharField(max_length=2000)),
                ('readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website_caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Film_part_caption', models.CharField(default='', max_length=2000)),
                ('Event_part_caption', models.CharField(default='', max_length=2000)),
                ('Marketing_part_caption', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
