# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contact_info_faq_film_link_visiter_message_website_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='youtube',
            field=models.CharField(default='', max_length=100),
        ),
    ]
