# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_contact_info_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiter_message',
            name='readed',
        ),
    ]
