# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_visiter_message_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='position_lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='position_lon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
