# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20160406_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_pic',
            field=models.ImageField(default='mainapp/image/no_img.jpg', upload_to='/home/vtoanb/ionsiteproject/ionsite/mainapp/static/mainapp/image'),
        ),
    ]
