# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20160407_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='mainapp/image/no_img.jpg', upload_to='/home/vtoanb/ionsiteproject/ionsite/static/mainapp/image'),
        ),
    ]
